[package]
name = "newstd"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
axum = { version = "0.7.4", features = ["macros", "tracing"] }
ext-php-rs = "0.12.0"
php-tokio = { path = "/home/thepiguy/Projects/php-tokio" }

[profile.release]
strip = "debugginginfo"
