version: '3'
services:
  nginx:
    image: docker.io/library/nginx:1.25.3-alpine
    volumes:
      - ./build/nginx.conf:/etc/nginx/nginx.conf
      - ./app/public:/app/public
    ports:
      - 8080:80
    depends_on:
      composer:
        condition: service_completed_successfully
  composer:
    image: composer:latest
    volumes:
      - ./vendor:/app/vendor
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
    command: ["install", "--no-dev"]
  php:
    build:
      context: .
      dockerfile: build/PHP.Dockerfile
    volumes:
      - ./app:/app
      - ./vendor:/app/vendor
      - ./build/zzz-docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
    environment:
      PS_DB_HOST: ${PS_DB_HOST}
      PS_DB_USERNAME: ${PS_DB_USERNAME}
      PS_DB_PASSWORD: ${PS_DB_PASSWORD}
      PS_DB_NAME: ${PS_DB_NAME}
      RESEND_API: ${RESEND_API}
      HOST_ADDR: ${HOST_ADDR}
      STRIPE_KEY: ${STRIPE_KEY}
    depends_on:
      composer:
        condition: service_completed_successfully
    command: php-fpm -R
  phpmyadmin:
    image: phpmyadmin:latest
#   volumes:
#     - ./build/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - 8081:80
    environment:
      PMA_HOST: ${PS_DB_HOST}
      PMA_USER: ${PS_DB_USERNAME}
      PMA_PASSWORD: ${PS_DB_PASSWORD}
