version: '3'
services:
  nginx:
    image: docker.io/library/nginx:1.25.3-alpine
    volumes:
      - ./build/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
  php:
    build:
      context: .
      dockerfile: build/PHP.Dockerfile
    volumes:
      - ./app:/app
    environment:
      # DB_TYPE: ${DB_TYPE}
      # DB_HOST: ${DB_HOST}
      # DB_NAME: ${DB_NAME}
      # DB_USER: ${DB_USER}
      # DB_PASS: ${DB_PASS}
      PS_DB_HOST: ${PS_DB_HOST}
      PS_DB_USERNAME: ${PS_DB_USERNAME}
      PS_DB_PASSWORD: ${PS_DB_PASSWORD}
      PS_DB_NAME: ${PS_DB_NAME}
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
        - 8081:80
    volumes:
      - /etc/ssl/certificate.crt:/etc/ssl/certificate.crt
    environment:
      PMA_HOST: ${PS_DB_HOST}
      PMA_USER: ${PS_DB_USERNAME}
      PMA_PASSWORD: ${PS_DB_PASSWORD}
    restart: unless-stopped
