on:
  push:
    branches:
      - main

jobs:
  check-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Check if Docker Compose is running
        run: |
          docker-compose up -d
          sleep 10
          docker-compose ps
